[tool.poetry]
name = "vss365today-finder"
version = "1.0.0"
description = "#vss365 prompt tweet finder service for #vss365 today"
authors = ["Caleb Ely <le717@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
apscheduler = "^3.6.3"
requests = "^2.23.0"
tweepy = "^3.8.0"
sys-vars = {url = "https://github.com/le717/sys-vars/releases/download/v3.0.0/sys_vars-3.0.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "^0.770"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
